### ISSUE TITLE
Overlay StaleElementReferenceError although it’s visible

### ISSUE THREAD

**Issue by anilpillai02** [sschwartzman/newrelic-synthetics-sebuilder#18]
[Costco_Checks copy.js.txt](https://github.com/sschwartzman/newrelic-synthetics-sebuilder/files/1442393/Costco_Checks.copy.js.txt)
 Hey Sschwartzman:
            

We have a container with a webform. Within the container there are "submit"/"next" buttons. When clicked, a new overlay is loaded with new webform elements.

Issue #1: The button is not consistently found on the first overlay although it is clearly visible. we can't get past this overly so I'm not sure the others would be found.
Issue #2: The elements on the subsequent overlays are not found although they are clearly visible.
  

Could you please shed some light for us on how to fix this ? I attached the full script for your reference 
Thanks for your help 

// Step 4
.then(function() {
	log(4, 'Product Details - Customize Breadcrumb');
	console.log('Select Duplicates');
	isTextPresent('Duplicates')
	.then(function(bool) {
		if(!bool) {
			console.log('verifyTextPresent: "Duplicates" FAILED');
			$browser.takeScreenshot();
			assert(false, 'Static Text Check: "Duplicates" was not found on ' + pageTitle);
		}
		else {
			console.log('verifyTextPresent: "Duplicates" SUCCEEDED');
		}
	});
	return $browser.findElement(By.id('MainContent_PartsPicker1_btnDuplicates')).isSelected()
	.then(function(checked) {
		if (!checked) {
			$browser.findElement(By.id('MainContent_PartsPicker1_btnDuplicates')).click();
		}
	})
	// Find Quantity dropdown
	.then(function() {
		return $browser.waitForAndFindElement(By.id('MainContent_ProductQuantity'), 5000)
		.then(function(quantity){
			dropdown = quantity;
			return $browser.actions().mouseMove(dropdown).perform()

			//Wait till dropdown opens to select option
			.then(function() { 
				return $browser.waitForAndFindElement(By.css('option[value="289"]'), 2000)
				.then(function(checks) {
					option = checks;
					option.click(); 
				})  
			})
		})
	})
	.then(function() {
		console.log('Click NEXT');
		return $browser.findElement(By.xpath('//*[@id="step1ContinueButton"]')).click()
	})
})

// Step 5
.then(function(){
	return $browser.waitForAndFindElement(By.name('ctl00$MainContent$Line1$Text'), 5000)
})

Here is the execution 

Step 0: Init STARTED at 1ms.
Step 0: Init FINISHED. It took 15ms to complete.
Step 1: Nagivate to Costco Checks STARTED at 16ms.
verifyTextPresent: "Best-Selling Personal Checks" SUCCEEDED
Step 1: Nagivate to Costco Checks FINISHED. It took 3444ms to complete.
Step 2: Personal -> Most Popular Checks STARTED at 3460ms.
verifyTextPresent: "Most Popular Checks" SUCCEEDED
Step 2: Personal -> Most Popular Checks FINISHED. It took 3360ms to complete.
Step 3: Select Blue Safety Checks STARTED at 6821ms.
verifyTextPresent: "Blue Safety Checks" SUCCEEDED
Step 3: Select Blue Safety Checks FINISHED. It took 2594ms to complete.
Step 4: Product Details - Customize Breadcrumb STARTED at 9416ms.
Select Duplicates
verifyTextPresent: "Duplicates" SUCCEEDED
Click NEXT
StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.31.488763 (092de99f48a300323ecf8c2a4e2e7cab51de5ba8),platform=Linux 4.9.36-x86_64-linode85 x86_64)
    at WebDriverError (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/error.js:27:5)
    at StaleElementReferenceError (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/error.js:235:5)
    at Object.checkLegacyResponse (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/error.js:529:15)
    at parseHttpResponse (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:109:7)
From: Task: WebElement.isDisplayed()
    at Driver.schedule (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebElement.schedule_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/webdriver.js:2015:25)
    at WebElement.isDisplayed (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/webdriver.js:2366:17)
    at /opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/until.js:303:20
    at /opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/webdriver.js:938:14
    at TaskQueue.execute_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:2982:25)
    at /opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:676:7
From: Task: <anonymous>
    at Timeout.pollCondition [as _onTimeout] (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:2203:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From: Task: Timed-out waiting for element to be visible using: By(css selector, *[name="ctl00\$MainContent\$Line1\$Text"])
    at scheduleWait (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:2196:20)
    at ControlFlow.wait (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:2525:12)
    at Driver.wait (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/webdriver.js:934:29)
    at Driver.<anonymous> (/opt/runtimes/3.0.0/modules/synthetics-runner/lib/webdriver/index.js:590:25)
    at ManagedPromise.invokeCallback_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:1384:14)
    at TaskQueue.execute_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:3092:14)
    at TaskQueue.executeNext_ (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:3075:27)
    at asyncRun (/opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:2935:27)
    at /opt/runtimes/3.0.0/node_modules/selenium-webdriver/lib/promise.js:676:7
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by sschwartzman** [comment]
Hi @anilpillai02 -  I saw this issue from a while back, sorry to just be responding now. You've probably figured this out by now, this issue is not one you're having with the Se-Builder or my plugin to it, but with Synthetics itself finding the element you're looking for. You'll need to debug in Synthetics (using "inspect element" in chrome might help show you options for what to label this element). You can also check with the [New Relic Explorers Hub](https://discuss.newrelic.com) for suggestions on what to do.
